### PR TITLE
fix: hidden explorer link if the pool's deal address is empty.

### PR DESCRIPTION
**Pull request by zhyd1997**
# Description

This PR closes #_, by:

- Updating 'a'
- Adding 'b'

### CODE REVIEW

**Review by saeta-eth — CHANGES_REQUESTED** [review]
Hey @zhyd1997

We don't want to hide the pool name. The issue is that we need to use `pool.address` instead of `pool.dealAddress`.

Do you want to address it? Thanks for contributing!

**Comment by zhyd1997** [comment]
Hi @saeta-eth 

From this line of code, the pool name (`title` props here) is not hidden:

https://github.com/AelinXYZ/aelin-frontend-v2/blob/20c8f83238753abbeace74edba87f5ef6a5dff71/src/components/pools/common/InfoCell.tsx#L75

**Comment by saeta-eth** [comment]
> Hi @saeta-eth
> 
> From this line of code, the pool name (`title` props here) is not hidden:
> 
> https://github.com/AelinXYZ/aelin-frontend-v2/blob/20c8f83238753abbeace74edba87f5ef6a5dff71/src/components/pools/common/InfoCell.tsx#L75

Not sure If I fully understand what you meant.
As far as I've read the code, the Name cell will be empty if `pool.dealAddress` is falsy.

**Comment by zhyd1997** [comment]
> > Hi @saeta-eth
> > From this line of code, the pool name (`title` props here) is not hidden:
> > https://github.com/AelinXYZ/aelin-frontend-v2/blob/20c8f83238753abbeace74edba87f5ef6a5dff71/src/components/pools/common/InfoCell.tsx#L75
> 
> Not sure If I fully understand what you meant. As far as I've read the code, the Name cell will be empty if `pool.dealAddress` is falsy.

the component to display the pool name is here?

https://github.com/AelinXYZ/aelin-frontend-v2/blob/20c8f83238753abbeace74edba87f5ef6a5dff71/src/components/pools/common/InfoCell.tsx#L64-L78

**Comment by zhyd1997** [comment]
the kwenta information component is included here: https://github.com/AelinXYZ/aelin-frontend-v2/blob/20c8f83238753abbeace74edba87f5ef6a5dff71/src/components/pools/deal/UpfrontDealInformation.tsx

I should change it also.

**Comment by zhyd1997** [comment]
@saeta-eth

Got it!

**Comment by zhyd1997** [comment]
> > Hi @saeta-eth
> > From this line of code, the pool name (`title` props here) is not hidden:
> > https://github.com/AelinXYZ/aelin-frontend-v2/blob/20c8f83238753abbeace74edba87f5ef6a5dff71/src/components/pools/common/InfoCell.tsx#L75
> 
> Not sure If I fully understand what you meant. As far as I've read the code, the Name cell will be empty if `pool.dealAddress` is falsy.

The pool name is displayed in `ExternalLink` as `label` props, sorry for misunderstanding 🙏🏿

**Comment by saeta-eth** [comment]
> > > Hi @saeta-eth
> > > From this line of code, the pool name (`title` props here) is not hidden:
> > > https://github.com/AelinXYZ/aelin-frontend-v2/blob/20c8f83238753abbeace74edba87f5ef6a5dff71/src/components/pools/common/InfoCell.tsx#L75
> > 
> > 
> > Not sure If I fully understand what you meant. As far as I've read the code, the Name cell will be empty if `pool.dealAddress` is falsy.
> 
> the component to display the pool name is here?
> 
> https://github.com/AelinXYZ/aelin-frontend-v2/blob/20c8f83238753abbeace74edba87f5ef6a5dff71/src/components/pools/common/InfoCell.tsx#L64-L78

We use this component to create the cells you see in the table. But the content is passed through the `value` prop. It's how it looks after your changes, that's what I have tried to said above.

Screen Shot 2022-11-14 at 01 22 03

**Comment by saeta-eth** [comment]
> the kwenta information component is included here: https://github.com/AelinXYZ/aelin-frontend-v2/blob/20c8f83238753abbeace74edba87f5ef6a5dff71/src/components/pools/deal/UpfrontDealInformation.tsx
> 
> I should change it also.

Hmm, the `DealInformation` is used only for pools and not for upfront deals. So, we need to rollback the change to this file.
`UpfrontDealInformation` is the component we're using for the Kwenta upfront deal. We only need to replace `pool.dealAddress` by `pool.address`

**Review by saeta-eth — APPROVED** [review]
hey @zhyd1997, it looks good to me. Thanks for the help, much appreciated!

**Comment by zhyd1997** [comment]
@saeta-eth sorry for wasting your so much time!

**Comment by saeta-eth** [comment]
> @saeta-eth sorry for wasting your so much time!

No problem. I love to receive feedback -and PRs-  from the community. :)

**Pull request merged**
